//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdotnet_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDiscountType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tDiscountType()
        {
            this.tCouponDetails = new HashSet<tCouponDetail>();
        }
    
        public int DiscountTypeID { get; set; }
        public string DiscountType { get; set; }
        public bool IsFree { get; set; }
        public bool IsPercentageDiscount { get; set; }
        public bool IsBOGO { get; set; }
        public Nullable<long> isAmountOff { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCouponDetail> tCouponDetails { get; set; }
    }
}
