//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdotnet_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEmplStatu
    {
        public int EmplStatusID { get; set; }
        public string EmplStatus { get; set; }
        public bool CanWork { get; set; }
        public Nullable<bool> IsEmployed { get; set; }
    }
}
