//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdotnet_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tProduct()
        {
            this.tCouponDetails = new HashSet<tCouponDetail>();
        }
    
        public int ProductID { get; set; }
        public string Status { get; set; }
        public string UPC_E { get; set; }
        public string UPC_A_ { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<decimal> PricePerSellableUnit { get; set; }
        public Nullable<int> NameID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ContainerID { get; set; }
        public Nullable<double> Size { get; set; }
        public Nullable<int> Size_UOMID { get; set; }
        public Nullable<double> I_Size { get; set; }
        public Nullable<int> I_UOMID { get; set; }
        public string Parent { get; set; }
        public string Count { get; set; }
        public string Endorsement_s_ { get; set; }
        public string Country { get; set; }
        public string Prepared___Notes___Health_Claims { get; set; }
        public Nullable<double> Serving_Size { get; set; }
        public Nullable<int> Serving_Size_UOMID { get; set; }
        public Nullable<double> I_Serving_Size { get; set; }
        public string I_Serving_Size_UOM { get; set; }
        public Nullable<int> I_Serving_Size_UOMID { get; set; }
        public string Pieces { get; set; }
        public Nullable<double> Servings_Per_Container { get; set; }
        public Nullable<double> Calories { get; set; }
        public string Fat_Calories { get; set; }
        public Nullable<double> Total_Fat_G { get; set; }
        public Nullable<double> Dvp_Total_Fat { get; set; }
        public string Saturated_Fat_G { get; set; }
        public string Dvp_Saturated_Fat { get; set; }
        public string Trans_Fat_G { get; set; }
        public string Dvp_Trans_Fat { get; set; }
        public string Polyunsaturated_Fat_G { get; set; }
        public string Monounsaturated_Fat_G { get; set; }
        public string Cholesterol_MG { get; set; }
        public string Dvp_Cholesterol { get; set; }
        public Nullable<double> Sodium_MG { get; set; }
        public Nullable<double> Dvp_Sodium { get; set; }
        public string Potassium_MG { get; set; }
        public string Dvp_Potassium { get; set; }
        public Nullable<double> Carbohydrates_G { get; set; }
        public Nullable<double> Dvp_Carbohydrates { get; set; }
        public string Fiber_G { get; set; }
        public string Dvp_Dietary_Fiber { get; set; }
        public Nullable<double> Sugars_G { get; set; }
        public string Dvp_Sugar { get; set; }
        public string Other_Carbohydrates_G { get; set; }
        public string Sugar_Alcohols_G { get; set; }
        public Nullable<double> Protein_G { get; set; }
        public string Dvp_Protein { get; set; }
        public Nullable<double> Net_Carbs_G { get; set; }
        public string Ingredients { get; set; }
        public string Warnings { get; set; }
        public string Allergy_Information { get; set; }
        public string Dvp_Vitamin_A { get; set; }
        public string Dvp_Vitamin_C { get; set; }
        public Nullable<double> Dvp_Calcium { get; set; }
        public string Dvp_Iron { get; set; }
        public Nullable<double> Dvp_Vitamin_D { get; set; }
        public string Dvp_Vitamin_E { get; set; }
        public string Dvp_Vitamin_K { get; set; }
        public string Dvp_Thiamin { get; set; }
        public string Dvp_Riboflavin { get; set; }
        public string Dvp_Niacin { get; set; }
        public string Dvp_Vitamin_B1 { get; set; }
        public Nullable<double> Dvp_Vitamin_B2 { get; set; }
        public string Dvp_Vitamin_B6 { get; set; }
        public Nullable<double> Dvp_Folic_Acid { get; set; }
        public string Dvp_Vitamin_B12 { get; set; }
        public string Dvp_Biotin { get; set; }
        public string DVP_Pantothenic_Acid { get; set; }
        public Nullable<double> Dvp_Phosphorus { get; set; }
        public Nullable<double> Dvp_Iodine { get; set; }
        public string Dvp_Magnesium { get; set; }
        public string Dvp_Zinc { get; set; }
        public string Dvp_Selenium { get; set; }
        public string Dvp_Copper { get; set; }
        public string Dvp_Manganese { get; set; }
        public string Dvp_Chromium { get; set; }
        public string Dvp_Molybdenum { get; set; }
        public string Dvp_Vitamin_B3 { get; set; }
        public string Dvp_Vitamin_B5 { get; set; }
        public string Dvp_Folate { get; set; }
        public string Soluble_Fiber { get; set; }
        public string Insoluble_Fiber { get; set; }
        public string Phosphate { get; set; }
        public string Chloride { get; set; }
        public Nullable<double> Caffeine_Mg { get; set; }
        public string Silica { get; set; }
        public string pH { get; set; }
        public string Bicarbonates { get; set; }
        public string Total_Dissolved_Solids { get; set; }
        public string Omega_3 { get; set; }
        public string Oleic_Acid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCouponDetail> tCouponDetails { get; set; }
    }
}
