//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdotnet_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStoreStatu
    {
        public int StoreStatusID { get; set; }
        public string StoreStatus { get; set; }
        public bool IsOpenForBusiness { get; set; }
        public bool IsClosedForever { get; set; }
    }
}
