//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdotnet_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStoreHistory
    {
        public int StoreHistoryID { get; set; }
        public int StoreID { get; set; }
        public System.DateTime StartDate { get; set; }
        public int StoreStatusID { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateStamp { get; set; }
    }
}
