//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdotnet_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTransaction()
        {
            this.tTransactionDetails = new HashSet<tTransactionDetail>();
        }
    
        public int TransactionID { get; set; }
        public System.TimeSpan TimeOfTransaction { get; set; }
        public System.DateTime DateOfTransaction { get; set; }
        public int StoreID { get; set; }
        public int LoyaltyID { get; set; }
        public int TransactionTypeID { get; set; }
        public int EmplID { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTransactionDetail> tTransactionDetails { get; set; }
    }
}
