//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdotnet_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTransactionDetail
    {
        public int TransactionDetailID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> QtyOfProduct { get; set; }
        public Nullable<decimal> PricePerSellableUnit { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CouponDetailID { get; set; }
    
        public virtual tTransaction tTransaction { get; set; }
    }
}
