//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdotnet_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmplGridViewReadOnly
    {
        public string Empl { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public bool IsSelfScan { get; set; }
        public string EmplTitle { get; set; }
        public string Store { get; set; }
        public string Address1 { get; set; }
    }
}
