//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdotnet_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmpl
    {
        public int EmplID { get; set; }
        public string Empl { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> EmplTitleID { get; set; }
        public bool IsSelfScan { get; set; }
    }
}
