//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdotnet_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmplCountWhoAreCurrentlyEmployedByStore
    {
        public int StoreID { get; set; }
        public string Store { get; set; }
        public Nullable<int> TotalEmployeesWhoAreEmployed { get; set; }
    }
}
