//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdotnet_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductSalesByHours_Prime
    {
        public Nullable<int> NameID { get; set; }
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public string Brand { get; set; }
        public Nullable<int> Qty { get; set; }
    }
}
