//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdotnet_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPurchaseTotal
    {
        public int TransactionID { get; set; }
        public System.TimeSpan TimeOfTransaction { get; set; }
        public System.DateTime DateOfTransaction { get; set; }
        public Nullable<decimal> SumOfTotalPrice { get; set; }
    }
}
